name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: debian:trixie
    strategy:
      fail-fast: false
      matrix:
        pg_version: [16, 17, 18]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pgrx
        with:
          pg_version: ${{ matrix.pg_version }}

      - name: Test
        run: cargo pgrx test "pg${{ matrix.pg_version }}"

      - name: Bench
        run: cargo pgrx bench "pg${{ matrix.pg_version }}"
