name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: debian:trixie
    strategy:
      fail-fast: false
      matrix:
        pg_version: [16, 17, 18]
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pgrx
        with:
          pg_version: ${{ matrix.pg_version }}

      - name: Install PostgreSQL server
        run: apt-get install -y postgresql-${{ matrix.pg_version }}

      - name: Create test user
        run: |
          useradd -m testuser
          chown -R testuser: .
          cp -r /github/home/.cargo /home/testuser/.cargo
          cp -r /github/home/.pgrx /home/testuser/.pgrx
          chown -R testuser: /home/testuser/.cargo /home/testuser/.pgrx

      - name: Test
        run: su testuser -c 'cargo pgrx test "pg${{ matrix.pg_version }}"'

      - name: Bench
        run: su testuser -c 'cargo pgrx bench "pg${{ matrix.pg_version }}"'
